language: python

python: "3.5"

services:
    - mongodb
    - elasticsearch
    - redis-server

env:
  global:
    - ACCEPT_HIGHCHARTS_LICENSE=1
    - HIGHCHARTS_VERSION=6.2.0
    - HIGHCHARTS_USE_STYLED=1
    - HIGHCHARTS_MOMENT=1

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install 6.10
    - nvm use 6.10
    - node --version
    - npm install -g npm

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

script:
    - cd server && flake8 && cd ..
    - cd client && node --max_old_space_size=4098 ./node_modules/.bin/grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..
